[project]
name = "map-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "geopandas>=1.0.1",
    "geopy>=2.4.1",
    "googlemaps>=4.10.0",
    "matplotlib>=3.10.0",
    "numpy>=2.2.0",
    "polars>=1.17.1",
    "rasterio>=1.4.3",
    "tqdm>=4.67.1",
    "utm>=0.7.0",
]
